### ISSUE TITLE
Immutant.org is down

### ISSUE THREAD

**Issue by staypufd** [immutant/immutant.org#11]
Tried to go to web site referenced in immutant GitHub project and request times out with no server found.

**Comment by tobias** [comment]
Hi @staypufd! I no longer have access to the infrastructure that hosts immuant.org, but @jcrossley3 should. Hey Jim, what's up?

**Comment by jcrossley3** [comment]
I'll see what I can do. sup tobes?

**Comment by jcrossley3** [comment]
@staypufd @tobias Can either of you build the site according to the docs in the README? If I could, I could publish it on github pages and alias the domain. Unfortunately, I get compiler errors building the nokogiri/therubyracer native extensions. I think I have the right devel libs installed. Is there a docker image that can build awestruct apps?

htf uses awestruct?!?! :)

**Comment by staypufd** [comment]
I can try this weekend. I haven’t used Ruby in a while so it’ll be interesting to get going again.I also wanted to chat with you all about what it would take from your educated guesses for me to undertake trying to make Immutant work on the latest Wildfly release.Thanks,Sam ***@***.*** from my iPhoneOn Dec 12, 2022, at 12:29 PM, Jim Crossley ***@***.***> wrote:﻿
@staypufd @tobias Can either of you build the site according to the docs in the README? If I could, I could publish it on github pages and alias the domain. Unfortunately, I get compiler errors building the nokogiri/therubyracer native extensions. I think I have the right devel libs installed. Is there a docker image that can build awestruct apps?
htf uses awestruct?!?! :)

**Comment by jcrossley3** [comment]
Ok, I ultimately punted on awestruct (project seems dead) and retrieved a copy of the static content from the wayback machine. I tweaked it a bit and put it in a new repo https://github.com/immutant/immutant.github.io which github treats as the pages for the org: http://immutant.github.io

I updated DNS to point http://immutant.org there as well.

Thanks for the report!

**Comment by tobias** [comment]
Thanks @jcrossley3! I too tried to build with awestruct, but ran in to all kinds of problems. 

I noticed projectodd.org is down as well, but c'est la vie.

**Comment by staypufd** [comment]
Thanks Jim and Tobias for looking into this and fixing up a new repo for it.
